=== ezYakaEagle442/Java-CSR-automation/Windows/DRS-signature/Java_Deployment_Rule_Set_DTD_v1.1.dtd
<!ELEMENT ruleset (rule*)>
<!ATTLIST ruleset version CDATA #REQUIRED>
 
<!ELEMENT rule (id, action)>
 
<!ELEMENT id (certificate?)>
<!ATTLIST id title CDATA #IMPLIED>
<!ATTLIST id location CDATA #IMPLIED>
 
<!ELEMENT certificate EMPTY>
<!ATTLIST certificate algorithm CDATA #IMPLIED>
<!ATTLIST certificate hash CDATA #REQUIRED>
 
<!ELEMENT action (message?)>
<!ATTLIST action permission (run | block | default) #REQUIRED>
<!ATTLIST action version CDATA #IMPLIED>
<!ATTLIST action force (true|false) "false">       <!-- introduced in 1.1 -->
 
<!ELEMENT message (#PCDATA)>
<!ATTLIST message locale CDATA #IMPLIED>

=== ezYakaEagle442/Java-CSR-automation/Windows/DRS-signature/ruleset.xml
<?xml version="1.0" encoding="utf-8"?>
<ruleset version="1.1+">
<!-- 
<ruleset version="1.2">
<!DOCTYPE document SYSTEM "Java_Deployment_Rule_Set_DTD_v1.1.dtd">
-->
<!-- 
* 
* Functional version: 1.0.0
* $Revision: 123 $
*
* To update RuleSet on CUW workstation: 
* 1.A Check DRS latest release version deployed on Production at \\mycompany.com\Dfs\OSS\Configuration_Packaging\JRE_RuleSet\PRD\JRE_DRS_latest_version.txt
* 1.B Check DRS version installed on workstation
* 1.C If available, check DRS latest Hotfix version at \\mycompany.com\Dfs\OSS\Configuration_Packaging\JRE_RuleSet\INC\JRE_DRS_latest_version.txt
*
* 2. PULL Production DRS from RAP ==> Collection JRE_Deployment_Rule_Set PULL [CEN00xxx]
* 
* 3. To Install a Hotfix specific to resolve an incident, add PC to collection name 
*    - for SD & "SD  L2"  : SD_JRE_Rule_Set_Install_v2.0_MUI_xMP_R2 - Install INC [CENxxx]
*    - for "DESKTOP L3" :JRE_Rule_Set_Install_update_V2_R2_INC - Install [CENxxx]
*
* Hotfix file location on DFS in case of Incident Management [INC] :
*  \\mycompany.com\Dfs\OSS\Configuration_Packaging\JRE_RuleSet\INC\DeploymentRuleSet.jar
*
* File location on DFS in case of Release Management: 
* - Production [PRD] :  \\mycompany.com\Dfs\OSS\Configuration_Packaging\JRE_RuleSet\PRD\DeploymentRuleSet.jar
* - Pilot [PLT] : \\mycompany.com\Dfs\OSS\Configuration_Packaging\JRE_RuleSet\PLT\DeploymentRuleSet.jar
* - UAT [UAT] : \\mycompany.com\Dfs\OSS\Configuration_Packaging\JRE_RuleSet\UAT\DeploymentRuleSet.jar
*
-->
  
  <!-- RuleSet -->

  <!-- allow anything signed with Corporate PKI cert for applications supporting JRE 8, the certificate expiration date is : dd/MM/YYYY -->
  <rule> 
    <id>
      <certificate algorithm="SHA-256" hash="" />
    </id>
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Internal Webapp running Java 8 SHA-256 authorized to run</message> -->
	</action>
  </rule> 
  
 
  <!-- Intranet portal -->
  <rule>
    <id location="intranet.eu.corp.mycompany.com" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Intranet portal Applet running Java 8 authorized to run URL intranet.eu.corp.mycompany.com</message> -->
	</action>
  </rule>
  <rule>
    <id location="https://intranet.eu.corp.mycompany.com" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Intranet portal Applet running Java 8 authorized to run URL https://intranet.eu.corp.mycompany.com </message> -->
	</action>
  </rule>  
  <rule>
    <id location="https://intranet-pprd.eu.corp.mycompany.com" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Intranet portal Applet running Java 8 authorized to run URL https://intranet-pprd.eu.corp.mycompany.com</message> -->
	</action>
  </rule>   
  
  <!-- Centreon Map  http://centreon.mycompany.com/centreon/modules/centreon-map-server/jws/ , the certificate expiration date is : dd/MM/YYYY  -->
  <rule>
    <id>
      <certificate algorithm="SHA-256" hash="xxx" />
    </id>
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Centreon Map running Java 8 authorized to run</message> -->
	</action>
  </rule>   
  
  <!-- CA spectrum http://spectrum.mycompany.com/spectrum/oneclick.jnlp , the certificate expiration date is : dd/MM/YYYY -->
  <rule>
    <!-- <certificate algorithm="SHA-256" hash="" /> -->
    <id location="spectrum.corp.mycompany.com" />
    <action permission="run" >
		<!-- <message>CA Spectrum running Java 8 authorized to run URL spectrum.corp.mycompany.com</message> -->
	</action>
  </rule>    
  <rule>
    <id location="10.0.0.1" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>CA Spectrum running Java 8 authorized to run URL with IP 10.0.0.1</message> -->
	</action>
  </rule>     
         
  <!-- Apps X -->
  <rule>
    <id location="devhost:8042" />
    <action permission="run" version="1.7.0_55" force="true" >
		<!-- <message>Run rule Apps X on specific port 8042</message> -->
	</action>	
  </rule>


  <!-- Define here Rules for Partners applications -->

	  <rule>
		<id location="*.your-partner.com" />
		<action permission="run"  >
		<!-- <message>PSA Applet running Java 8 authorized to run from URL *.partners.com</message> -->
		</action>		
	  </rule>
	  
	
  <!-- end of Partner rules -->
  
  <!-- Define here Rules for local applications -->
  
  <!-- EUR -->
  
	<!-- Spain -->
	<rule>
		<id location="https://partner-sp.es" />
		<action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Spain local Application running Java 8 authorized to run from URL partner-sp</message> -->
		</action>			
	</rule>

	
	<!-- End of Spain rules -->
	
	<!-- France -->	
	<rule>
		<id location="https://www.hr.csod.com" />
		<action permission="run" version="1.8.0_131" force="true" >
			<!-- <message>Rule to allow HR SaaS location https://www.hr.csod.com : RUN permission allowed</message> -->
		</action>
	</rule>	
	<!-- End of France rules -->
	
  <!-- APAC -->
  

  <!-- AMEI -->
  
  <!-- LATAM -->
  
  <!-- US -->
  
  
  <!-- Anything signed with this Dev PKI certificate for applications running JRE 6 is NOT allowed in PRODUCTION  -->
  <rule> 
    <id>
      <certificate algorithm="SHA-256" hash="xxx" />
    </id>
    <action permission="block" version="1.6.0_45" force="true" >
		<message>XXXX  Webapp running Java 6 NOT authorized to run in Production</message>
	</action>	
  </rule>
 
      
  <!-- Default rule : run all by default with latest JRE version -->
  <!-- 
  see https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Country_code_top-level_domains
  https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains
  -->

  <!-- 
  http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/deployment_rules.html#A1150376
   If a rule set is reported as invalid, then check for the following problems based on the error you received:
   
##A rule with an action of run has no selection criteria provided and therefore matches all RIAs.
##The file is unreadable.
##The structure of the file is invalid.
##The rules are not properly defined.
##The JAR file is not properly signed with a valid certificate.
  -->
  
  <!-- Default rule : run all by default with latest JRE version 
  
  ==> this <id /> syntax does not work when RUN permission is set ...
  
  Oracle documentation is unclear regarding ability to RUN any application by default :
	- If the location attribute is not present, or the value is null, then the location matches all RIAs. 
	- The host name cannot be just an asterisk.
	- If a rule set is reported as invalid, then check if a rule with an action of run has no selection criteria provided and therefore matches all RIAs.


  -->
  
  <rule>
    <id location="*.org" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.org to allow any location: RUN permission allowed</message> -->
	</action>
  </rule>
   
  <rule>
    <id location="*.com" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.com to allow any location: RUN permission allowed</message> -->
	</action>
  </rule>
  
  <rule>
    <id location="*.net" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.net to allow any location: RUN permission allowed</message> -->
	</action>
  </rule>  
  
  <rule>
    <id location="*.eu" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.eu to allow any location: RUN permission allowed</message> -->
	</action>
  </rule> 
  
  <rule>
    <id location="*.edu" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.edu to allow any location: RUN permission allowed</message> -->
	</action>
  </rule> 
  
  <rule>
    <id location="*.gov" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.gov to allow any location: RUN permission allowed</message> -->
	</action>
  </rule> 
  
  <rule>
    <id location="*.fr" />
    <action permission="run" version="1.8.0_131" force="true" >
		<!-- <message>Default rule with wildcard *.fr to allow any location: RUN permission allowed</message> -->
	</action>
  </rule>
  
  <rule>
    <id location="*.ac"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.ad"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.ae"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.af"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.ag"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.ai"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.al"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.am"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.an"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.ao"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.aq"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.ar"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.as"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
    <id location="*.at"/>
    <action permission="run" version="1.8.0_131" force="true" />
  </rule>
  <rule>
